API Debugging
Nah, looks like you can't use simple functionality like addition either. So I think the output from AssemblyScript is more intrinsically tied to that of the JS context it's intended to be used with.

```sh
brandon@hackbook:dist$ wasmer ./index.wasm
error: The module doesn't contain a "_start" function. Either implement it or specify an entrypoint function.
╰─▶ 1: Missing export _start
```